import { Category } from "@/types/prompt";

export const appearance: Category[] = [
  {
    id: "gender",
    name: "Gender/Sex",
    description: "The gender or sex of the character",
    options: [
      { id: "male", name: "Male", value: "male" },
      { id: "female", name: "Female", value: "female" },
      { id: "nonbinary", name: "Non-binary", value: "non-binary" },
      { id: "androgynous", name: "Androgynous", value: "androgynous" },
    ]
  },
  {
    id: "bodyType",
    name: "Body Type",
    description: "Physical characteristics and body types",
    options: [
      { id: "athletic", name: "Athletic", value: "athletic build" },
      { id: "slim", name: "Slim", value: "slim figure" },
      { id: "curvy", name: "Curvy", value: "curvy figure" },
      { id: "muscular", name: "Muscular", value: "muscular build" },
      { id: "petite", name: "Petite", value: "petite frame" },
      { id: "plus-size", name: "Plus Size", value: "plus size" },
      { id: "tall", name: "Tall", value: "tall stature" },
      { id: "short", name: "Short", value: "short stature" },
      { id: "average", name: "Average", value: "average build" },
      { id: "pregnant", name: "Pregnant", value: "pregnant" },
      { id: "bodybuilder", name: "Bodybuilder", value: "bodybuilder physique" },
      { id: "lanky", name: "Lanky", value: "lanky frame" },
      { id: "pear-shaped", name: "Pear-shaped", value: "pear-shaped" },
      { id: "hourglass", name: "Hourglass", value: "hourglass figure" },
      { id: "rectangular", name: "Rectangular", value: "rectangular build" },
      { id: "thin", name: "Thin", value: "thin" },
    ]
  },
  {
    id: "clothing",
    name: "Clothing/Attire",
    description: "Clothing and fashion styles",
    options: [
      { id: "casual", name: "Casual", value: "casual attire" },
      { id: "formal", name: "Formal", value: "formal attire" },
      { id: "business", name: "Business", value: "business attire" },
      { id: "vintage", name: "Vintage", value: "vintage clothing" },
      { id: "futuristic", name: "Futuristic", value: "futuristic clothing" },
      { id: "minimal", name: "Minimalist", value: "minimalist clothing" },
      { id: "streetwear", name: "Streetwear", value: "streetwear" },
      { id: "athleisure", name: "Athleisure", value: "athleisure" },
      { id: "haute-couture", name: "Haute Couture", value: "haute couture" },
      { id: "gothic", name: "Gothic", value: "gothic attire" },
      { id: "punk", name: "Punk", value: "punk fashion" },
      { id: "bohemian", name: "Bohemian", value: "bohemian clothing" },
      { id: "retro", name: "Retro", value: "retro clothing" },
      { id: "traditional", name: "Traditional", value: "traditional clothing" },
      { id: "swimwear", name: "Swimwear", value: "swimwear" },
      { id: "uniform", name: "Uniform", value: "uniform" },
      { id: "sportswear", name: "Sportswear", value: "sportswear" },
      { id: "evening-wear", name: "Evening Wear", value: "evening wear" },
      { id: "medieval", name: "Medieval", value: "medieval clothing" },
      { id: "renaissance", name: "Renaissance", value: "renaissance clothing" },
      { id: "cyberpunk", name: "Cyberpunk", value: "cyberpunk clothing" },
      { id: "steampunk", name: "Steampunk", value: "steampunk clothing" },
    ]
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Accessories and decorative elements",
    options: [
      { id: "jewelry", name: "Jewelry", value: "jewelry" },
      { id: "hat", name: "Hat", value: "hat" },
      { id: "glasses", name: "Glasses", value: "glasses" },
      { id: "watch", name: "Watch", value: "watch" },
      { id: "scarf", name: "Scarf", value: "scarf" },
      { id: "handbag", name: "Handbag", value: "handbag" },
      { id: "backpack", name: "Backpack", value: "backpack" },
      { id: "crown", name: "Crown/Tiara", value: "crown" },
      { id: "mask", name: "Mask", value: "mask" },
      { id: "tattoos", name: "Tattoos", value: "tattoos" },
      { id: "piercings", name: "Piercings", value: "piercings" },
      { id: "headphones", name: "Headphones", value: "headphones" },
      { id: "sunglasses", name: "Sunglasses", value: "sunglasses" },
      { id: "belt", name: "Belt", value: "belt" },
      { id: "gloves", name: "Gloves", value: "gloves" },
      { id: "tie", name: "Tie", value: "tie" },
      { id: "necklace", name: "Necklace", value: "necklace" },
      { id: "earrings", name: "Earrings", value: "earrings" },
      { id: "bracelet", name: "Bracelet", value: "bracelet" },
      { id: "umbrella", name: "Umbrella", value: "umbrella" },
    ]
  },
  {
    id: "expression",
    name: "Expression/Emotion",
    description: "Facial expressions and emotional states",
    options: [
      { id: "happy", name: "Happy", value: "happy expression" },
      { id: "sad", name: "Sad", value: "sad expression" },
      { id: "angry", name: "Angry", value: "angry expression" },
      { id: "surprised", name: "Surprised", value: "surprised expression" },
      { id: "thoughtful", name: "Thoughtful", value: "thoughtful expression" },
      { id: "neutral", name: "Neutral", value: "neutral expression" },
      { id: "laughing", name: "Laughing", value: "laughing" },
      { id: "crying", name: "Crying", value: "crying" },
      { id: "smiling", name: "Smiling", value: "smiling" },
      { id: "frowning", name: "Frowning", value: "frowning" },
      { id: "confused", name: "Confused", value: "confused expression" },
      { id: "excited", name: "Excited", value: "excited expression" },
      { id: "tired", name: "Tired", value: "tired expression" },
      { id: "worried", name: "Worried", value: "worried expression" },
      { id: "determined", name: "Determined", value: "determined expression" },
      { id: "suspicious", name: "Suspicious", value: "suspicious expression" },
      { id: "confident", name: "Confident", value: "confident expression" },
      { id: "shy", name: "Shy", value: "shy expression" },
      { id: "proud", name: "Proud", value: "proud expression" },
    ]
  },
  {
    id: "pose",
    name: "Pose/Stance",
    description: "Body poses and stances",
    options: [
      { id: "standing", name: "Standing", value: "standing pose" },
      { id: "sitting", name: "Sitting", value: "sitting pose" },
      { id: "lying", name: "Lying Down", value: "lying down" },
      { id: "walking", name: "Walking", value: "walking" },
      { id: "running", name: "Running", value: "running" },
      { id: "jumping", name: "Jumping", value: "jumping" },
      { id: "dancing", name: "Dancing", value: "dancing" },
      { id: "leaning", name: "Leaning", value: "leaning" },
      { id: "crouching", name: "Crouching", value: "crouching" },
      { id: "kneeling", name: "Kneeling", value: "kneeling" },
      { id: "floating", name: "Floating", value: "floating" },
      { id: "action", name: "Action Pose", value: "action pose" },
      { id: "yoga", name: "Yoga Pose", value: "yoga pose" },
      { id: "meditation", name: "Meditation", value: "meditation pose" },
      { id: "elegant", name: "Elegant Pose", value: "elegant pose" },
      { id: "dynamic", name: "Dynamic Pose", value: "dynamic pose" },
      { id: "power", name: "Power Stance", value: "power stance" },
      { id: "contrapposto", name: "Contrapposto", value: "contrapposto pose" },
      { id: "casual", name: "Casual Pose", value: "casual pose" },
      { id: "formal", name: "Formal Pose", value: "formal pose" },
    ]
  },
  {
    id: "hairStyle",
    name: "Hair Style",
    description: "Hair styles and colors",
    options: [
      { id: "long", name: "Long Hair", value: "long hair" },
      { id: "short", name: "Short Hair", value: "short hair" },
      { id: "curly", name: "Curly Hair", value: "curly hair" },
      { id: "straight", name: "Straight Hair", value: "straight hair" },
      { id: "wavy", name: "Wavy Hair", value: "wavy hair" },
      { id: "bald", name: "Bald", value: "bald" },
      { id: "braided", name: "Braided", value: "braided hair" },
      { id: "ponytail", name: "Ponytail", value: "ponytail" },
      { id: "bun", name: "Bun", value: "hair bun" },
      { id: "pixie-cut", name: "Pixie Cut", value: "pixie cut" },
      { id: "mohawk", name: "Mohawk", value: "mohawk" },
      { id: "afro", name: "Afro", value: "afro" },
      { id: "dreadlocks", name: "Dreadlocks", value: "dreadlocks" },
      { id: "colored-hair", name: "Colored Hair", value: "colored hair" },
      { id: "blonde", name: "Blonde", value: "blonde hair" },
      { id: "brunette", name: "Brunette", value: "brunette hair" },
      { id: "red-hair", name: "Red Hair", value: "red hair" },
      { id: "black-hair", name: "Black Hair", value: "black hair" },
      { id: "gray-hair", name: "Gray Hair", value: "gray hair" },
      { id: "white-hair", name: "White Hair", value: "white hair" },
      { id: "pink-hair", name: "Pink Hair", value: "pink hair" },
      { id: "blue-hair", name: "Blue Hair", value: "blue hair" },
      { id: "green-hair", name: "Green Hair", value: "green hair" },
      { id: "purple-hair", name: "Purple Hair", value: "purple hair" },
    ]
  },
];
