
import { Category } from "@/types/prompt";

export const composition: Category[] = [
  {
    id: "composition",
    name: "Composition",
    description: "How the image is composed",
    options: [
      { id: "rule-thirds", name: "Rule of Thirds", value: "rule of thirds" },
      { id: "symmetrical", name: "Symmetrical", value: "symmetrical composition" },
      { id: "minimalist", name: "Minimalist", value: "minimalist composition" },
      { id: "complex", name: "Complex", value: "complex composition" },
      { id: "dynamic", name: "Dynamic", value: "dynamic composition" },
      { id: "centered", name: "Centered", value: "centered composition" },
      { id: "panoramic", name: "Panoramic", value: "panoramic" },
      { id: "closeup", name: "Close-up", value: "close-up" },
      { id: "aerial", name: "Aerial View", value: "aerial view" },
      { id: "isometric", name: "Isometric", value: "isometric" },
      { id: "framed", name: "Framed", value: "framed composition" },
      { id: "layered", name: "Layered", value: "layered composition" },
      { id: "diagonal", name: "Diagonal", value: "diagonal composition" },
      { id: "triangle", name: "Triangle", value: "triangular composition" },
      { id: "radial", name: "Radial", value: "radial composition" },
      { id: "golden-ratio", name: "Golden Ratio", value: "golden ratio" },
      { id: "wide-angle", name: "Wide Angle", value: "wide angle composition" },
      { id: "telephoto", name: "Telephoto", value: "telephoto composition" },
      { id: "dutch-angle", name: "Dutch Angle", value: "dutch angle" },
      { id: "bird's-eye", name: "Bird's-Eye View", value: "bird's-eye view" },
      { id: "worm's-eye", name: "Worm's-Eye View", value: "worm's-eye view" },
      { id: "split-field", name: "Split-Field", value: "split-field composition" },
      { id: "triptych", name: "Triptych", value: "triptych" },
      { id: "quadriptych", name: "Quadriptych", value: "quadriptych" },
    ]
  },
  {
    id: "angle",
    name: "Camera Angle",
    description: "Viewing angle of the subject",
    options: [
      { id: "eye-level", name: "Eye Level", value: "eye level shot" },
      { id: "high-angle", name: "High Angle", value: "high angle shot" },
      { id: "low-angle", name: "Low Angle", value: "low angle shot" },
      { id: "overhead", name: "Overhead", value: "overhead shot" },
      { id: "birds-eye", name: "Bird's Eye View", value: "bird's eye view" },
      { id: "worms-eye", name: "Worm's Eye View", value: "worm's eye view" },
      { id: "dutch-angle", name: "Dutch Angle", value: "dutch angle" },
      { id: "profile", name: "Profile", value: "profile view" },
      { id: "three-quarter", name: "Three-Quarter", value: "three-quarter view" },
      { id: "front", name: "Front View", value: "front view" },
      { id: "back", name: "Back View", value: "back view" },
      { id: "over-the-shoulder", name: "Over-the-Shoulder", value: "over-the-shoulder shot" },
      { id: "extreme-closeup", name: "Extreme Close-Up", value: "extreme close-up" },
      { id: "medium-shot", name: "Medium Shot", value: "medium shot" },
      { id: "wide-shot", name: "Wide Shot", value: "wide shot" },
      { id: "establishing-shot", name: "Establishing Shot", value: "establishing shot" },
    ]
  },
  {
    id: "camera",
    name: "Camera Settings",
    description: "Camera and photography details",
    options: [
      { id: "bokeh", name: "Bokeh Effect", value: "bokeh effect" },
      { id: "shallow-dof", name: "Shallow Depth of Field", value: "shallow depth of field" },
      { id: "deep-dof", name: "Deep Depth of Field", value: "deep depth of field" },
      { id: "macro", name: "Macro", value: "macro photography" },
      { id: "telephoto", name: "Telephoto Lens", value: "telephoto lens" },
      { id: "wide-angle", name: "Wide Angle", value: "wide angle" },
      { id: "fisheye", name: "Fisheye", value: "fisheye lens" },
      { id: "long-exposure", name: "Long Exposure", value: "long exposure" },
      { id: "tilt-shift", name: "Tilt-Shift", value: "tilt-shift" },
      { id: "polarizing", name: "Polarizing Filter", value: "polarizing filter" },
      { id: "hdr", name: "HDR", value: "HDR" },
      { id: "motion-blur", name: "Motion Blur", value: "motion blur" },
      { id: "drone", name: "Drone Shot", value: "drone shot" },
      { id: "360-degree", name: "360-Degree", value: "360-degree" },
      { id: "time-lapse", name: "Time-Lapse", value: "time-lapse" },
      { id: "night-vision", name: "Night Vision", value: "night vision" },
      { id: "prime-lens", name: "Prime Lens", value: "prime lens" },
      { id: "soft-focus", name: "Soft Focus", value: "soft focus" },
      { id: "infrared", name: "Infrared", value: "infrared" },
      { id: "panoramic", name: "Panoramic", value: "panoramic camera" },
      { id: "underwater", name: "Underwater Camera", value: "underwater camera" },
      { id: "f1.4", name: "f/1.4 Aperture", value: "f/1.4 aperture" },
      { id: "f16", name: "f/16 Aperture", value: "f/16 aperture" },
      { id: "iso100", name: "ISO 100", value: "ISO 100" },
    ]
  },
  {
    id: "camera_type",
    name: "Taken on",
    description: "Camera equipment used to take the photo",
    options: [
      { id: "smartphone", name: "Smartphone", value: "taken on smartphone" },
      { id: "iphone", name: "iPhone", value: "taken on iPhone" },
      { id: "google-pixel", name: "Google Pixel", value: "taken on Google Pixel" },
      { id: "dslr", name: "DSLR", value: "taken on DSLR" },
      { id: "mirrorless", name: "Mirrorless", value: "taken on mirrorless camera" },
      { id: "leica", name: "Leica", value: "taken on Leica" },
      { id: "canon", name: "Canon", value: "taken on Canon" },
      { id: "nikon", name: "Nikon", value: "taken on Nikon" },
      { id: "sony", name: "Sony", value: "taken on Sony" },
      { id: "fujifilm", name: "Fujifilm", value: "taken on Fujifilm" },
      { id: "hasselblad", name: "Hasselblad", value: "taken on Hasselblad" },
      { id: "polaroid", name: "Polaroid", value: "taken on Polaroid" },
      { id: "disposable", name: "Disposable Camera", value: "taken on disposable camera" },
      { id: "film-camera", name: "Film Camera", value: "taken on film camera" },
      { id: "medium-format", name: "Medium Format", value: "taken on medium format camera" },
      { id: "large-format", name: "Large Format", value: "taken on large format camera" },
      { id: "gopro", name: "GoPro", value: "taken on GoPro" },
      { id: "drone", name: "Drone", value: "taken with drone" },
      { id: "webcam", name: "Webcam", value: "taken on webcam" },
      { id: "point-and-shoot", name: "Point-and-Shoot", value: "taken on point-and-shoot camera" },
    ]
  },
  {
    id: "color_grading",
    name: "Color Grading",
    description: "Film stocks and color processing techniques",
    options: [
      { id: "kodachrome", name: "Kodachrome", value: "Kodachrome film" },
      { id: "ektachrome", name: "Ektachrome", value: "Ektachrome film" },
      { id: "portra", name: "Portra 400", value: "Portra 400 film" },
      { id: "portra-800", name: "Portra 800", value: "Portra 800 film" },
      { id: "fuji-velvia", name: "Fuji Velvia", value: "Fuji Velvia film" },
      { id: "fuji-provia", name: "Fuji Provia", value: "Fuji Provia film" },
      { id: "fuji-superia", name: "Fuji Superia", value: "Fuji Superia film" },
      { id: "ilford-hp5", name: "Ilford HP5", value: "Ilford HP5 film" },
      { id: "ilford-delta", name: "Ilford Delta", value: "Ilford Delta film" },
      { id: "tri-x", name: "Tri-X", value: "Tri-X film" },
      { id: "cinestill-800t", name: "CineStill 800T", value: "CineStill 800T film" },
      { id: "lomo", name: "Lomography", value: "Lomography film" },
      { id: "cross-processed", name: "Cross Processed", value: "cross processed film" },
      { id: "bleach-bypass", name: "Bleach Bypass", value: "bleach bypass process" },
      { id: "technicolor", name: "Technicolor", value: "Technicolor process" },
      { id: "vintage-tint", name: "Vintage Tint", value: "vintage color tint" },
      { id: "orange-teal", name: "Orange & Teal", value: "orange and teal color grade" },
      { id: "sepia", name: "Sepia", value: "sepia tone" },
      { id: "cyanotype", name: "Cyanotype", value: "cyanotype process" },
      { id: "daguerreotype", name: "Daguerreotype", value: "daguerreotype process" },
    ]
  },
];
