import { Category } from "@/types/prompt";

export const environment: Category[] = [
  {
    id: "place",
    name: "Specific Place",
    description: "Specific locations or places",
    options: [
      // Common rooms in a house
      { id: "living-room", name: "Living Room", value: "living room" },
      { id: "bathroom", name: "Bathroom", value: "bathroom" },
      { id: "bedroom", name: "Bedroom", value: "bedroom" },
      { id: "kitchen", name: "Kitchen", value: "kitchen" },
      { id: "dining-room", name: "Dining Room", value: "dining room" },
      { id: "home-office", name: "Home Office", value: "home office" },
      { id: "hallway", name: "Hallway", value: "hallway" },
      { id: "basement", name: "Basement", value: "basement" },
      { id: "attic", name: "Attic", value: "attic" },
      { id: "nursery", name: "Nursery", value: "nursery" },
      { id: "garage", name: "Garage", value: "garage" },
      { id: "laundry-room", name: "Laundry Room", value: "laundry room" },
      { id: "sunroom", name: "Sunroom", value: "sunroom" },
      { id: "pantry", name: "Pantry", value: "pantry" },
      { id: "walk-in-closet", name: "Walk-in Closet", value: "walk-in closet" },
      
      // Outdoor spaces of a house
      { id: "balcony", name: "Balcony", value: "balcony" },
      { id: "patio", name: "Patio", value: "patio" },
      { id: "backyard", name: "Backyard", value: "backyard" },
      { id: "front-yard", name: "Front Yard", value: "front yard" },
      { id: "porch", name: "Porch", value: "porch" },
      { id: "garden", name: "Garden", value: "garden" },
      
      // Keep existing locations
      { id: "beach", name: "Beach", value: "beach" },
      { id: "mountain", name: "Mountain", value: "mountain" },
      { id: "forest", name: "Forest", value: "forest" },
      { id: "desert", name: "Desert", value: "desert" },
      { id: "city-street", name: "City Street", value: "city street" },
      { id: "cafe", name: "Cafe", value: "cafe" },
      { id: "library", name: "Library", value: "library" },
      { id: "park", name: "Park", value: "park" },
      { id: "studio", name: "Studio", value: "studio" },
      { id: "museum", name: "Museum", value: "museum" },
      { id: "theater", name: "Theater", value: "theater" },
      { id: "subway", name: "Subway", value: "subway" },
      { id: "rooftop", name: "Rooftop", value: "rooftop" },
      { id: "office", name: "Office", value: "office" },
      { id: "laboratory", name: "Laboratory", value: "laboratory" },
      { id: "ancient-ruins", name: "Ancient Ruins", value: "ancient ruins" },
      { id: "cave", name: "Cave", value: "cave" },
      { id: "waterfall", name: "Waterfall", value: "waterfall" },
      { id: "palace", name: "Palace", value: "palace" },
      { id: "train-station", name: "Train Station", value: "train station" },
      { id: "airport", name: "Airport", value: "airport" },
    ]
  },
  {
    id: "weather",
    name: "Weather",
    description: "Weather conditions",
    options: [
      { id: "sunny", name: "Sunny", value: "sunny weather" },
      { id: "rainy", name: "Rainy", value: "rainy weather" },
      { id: "snowy", name: "Snowy", value: "snowy weather" },
      { id: "cloudy", name: "Cloudy", value: "cloudy weather" },
      { id: "foggy", name: "Foggy", value: "foggy weather" },
      { id: "stormy", name: "Stormy", value: "stormy weather" },
      { id: "windy", name: "Windy", value: "windy conditions" },
      { id: "hazy", name: "Hazy", value: "hazy conditions" },
      { id: "misty", name: "Misty", value: "misty conditions" },
      { id: "lightning", name: "Lightning", value: "lightning" },
      { id: "rainbow", name: "Rainbow", value: "rainbow" },
      { id: "hail", name: "Hail", value: "hailstorm" },
      { id: "blizzard", name: "Blizzard", value: "blizzard" },
      { id: "tornado", name: "Tornado", value: "tornado" },
      { id: "hurricane", name: "Hurricane", value: "hurricane" },
      { id: "clear-night", name: "Clear Night", value: "clear night sky" },
    ]
  },
  {
    id: "timeOfDay",
    name: "Time of Day",
    description: "Different times of day",
    options: [
      { id: "dawn", name: "Dawn", value: "dawn" },
      { id: "morning", name: "Morning", value: "morning" },
      { id: "noon", name: "Noon", value: "noon" },
      { id: "afternoon", name: "Afternoon", value: "afternoon" },
      { id: "sunset", name: "Sunset", value: "sunset" },
      { id: "dusk", name: "Dusk", value: "dusk" },
      { id: "evening", name: "Evening", value: "evening" },
      { id: "night", name: "Night", value: "night" },
      { id: "midnight", name: "Midnight", value: "midnight" },
      { id: "golden-hour", name: "Golden Hour", value: "golden hour" },
      { id: "blue-hour", name: "Blue Hour", value: "blue hour" },
    ]
  },
  {
    id: "season",
    name: "Season",
    description: "Different seasons of the year",
    options: [
      { id: "spring", name: "Spring", value: "spring" },
      { id: "summer", name: "Summer", value: "summer" },
      { id: "autumn", name: "Autumn/Fall", value: "autumn" },
      { id: "winter", name: "Winter", value: "winter" },
      { id: "monsoon", name: "Monsoon", value: "monsoon season" },
      { id: "dry-season", name: "Dry Season", value: "dry season" },
      { id: "wet-season", name: "Wet Season", value: "wet season" },
      { id: "cherry-blossom", name: "Cherry Blossom", value: "cherry blossom season" },
      { id: "harvest", name: "Harvest", value: "harvest season" },
    ]
  },
  {
    id: "setting",
    name: "Setting/Environment",
    description: "The location or environment",
    options: [
      { id: "urban", name: "Urban", value: "urban environment" },
      { id: "nature", name: "Nature", value: "natural environment" },
      { id: "futuristic", name: "Futuristic", value: "futuristic environment" },
      { id: "historic", name: "Historic", value: "historic setting" },
      { id: "fantasy", name: "Fantasy", value: "fantasy world" },
      { id: "space", name: "Space", value: "outer space" },
      { id: "underwater", name: "Underwater", value: "underwater" },
      { id: "desert", name: "Desert", value: "desert" },
      { id: "arctic", name: "Arctic/Snowy", value: "arctic/snowy environment" },
      { id: "jungle", name: "Jungle", value: "jungle" },
      { id: "dystopian", name: "Dystopian", value: "dystopian" },
      { id: "cyberpunk", name: "Cyberpunk", value: "cyberpunk city" },
      { id: "steampunk", name: "Steampunk", value: "steampunk" },
      { id: "coast", name: "Coastal", value: "coastal" },
      { id: "mountains", name: "Mountains", value: "mountains" },
      { id: "ruins", name: "Ruins", value: "ruins" },
      { id: "city", name: "City", value: "city" },
      { id: "village", name: "Village", value: "village" },
      { id: "castle", name: "Castle", value: "castle" },
      { id: "temple", name: "Temple", value: "temple" },
      { id: "spaceship", name: "Spaceship", value: "spaceship" },
      { id: "laboratory", name: "Laboratory", value: "laboratory" },
      { id: "island", name: "Island", value: "island" },
      { id: "forest", name: "Forest", value: "forest" },
    ]
  },
  {
    id: "era",
    name: "Time Period",
    description: "Historical era or time period",
    options: [
      { id: "prehistoric", name: "Prehistoric", value: "prehistoric" },
      { id: "ancient", name: "Ancient", value: "ancient" },
      { id: "medieval", name: "Medieval", value: "medieval" },
      { id: "renaissance", name: "Renaissance", value: "renaissance" },
      { id: "industrial", name: "Industrial", value: "industrial era" },
      { id: "victorian", name: "Victorian", value: "victorian era" },
      { id: "1920s", name: "1920s", value: "1920s" },
      { id: "1950s", name: "1950s", value: "1950s" },
      { id: "1980s", name: "1980s", value: "1980s" },
      { id: "modern", name: "Modern", value: "modern" },
      { id: "futuristic", name: "Futuristic", value: "futuristic" },
      { id: "post-apocalyptic", name: "Post-Apocalyptic", value: "post-apocalyptic" },
      { id: "bronze-age", name: "Bronze Age", value: "bronze age" },
      { id: "iron-age", name: "Iron Age", value: "iron age" },
      { id: "baroque", name: "Baroque", value: "baroque" },
      { id: "art-deco", name: "Art Deco", value: "art deco" },
      { id: "ancient-egypt", name: "Ancient Egypt", value: "ancient egypt" },
      { id: "ancient-rome", name: "Ancient Rome", value: "ancient rome" },
      { id: "ancient-greece", name: "Ancient Greece", value: "ancient greece" },
      { id: "edo-period", name: "Edo Period", value: "edo period" },
      { id: "wild-west", name: "Wild West", value: "wild west" },
      { id: "roaring-twenties", name: "Roaring Twenties", value: "roaring twenties" },
      { id: "golden-age-hollywood", name: "Golden Age of Hollywood", value: "golden age of hollywood" },
      { id: "digital-age", name: "Digital Age", value: "digital age" },
    ]
  },
];
