
import { Category } from "@/types/prompt";

export const style: Category[] = [
  {
    id: "style",
    name: "Art Style",
    description: "The artistic style of the image",
    options: [
      { id: "realistic", name: "Photorealistic", value: "photorealistic" },
      { id: "digital-art", name: "Digital Art", value: "digital art" },
      { id: "anime", name: "Anime/Manga", value: "anime" },
      { id: "painting", name: "Painting", value: "painting" },
      { id: "3d-render", name: "3D Render", value: "3D render" },
      { id: "concept-art", name: "Concept Art", value: "concept art" },
      { id: "illustration", name: "Illustration", value: "illustration" },
      { id: "fantasy", name: "Fantasy", value: "fantasy art" },
      { id: "sci-fi", name: "Sci-Fi", value: "sci-fi art" },
      { id: "pixel-art", name: "Pixel Art", value: "pixel art" },
      { id: "abstract", name: "Abstract", value: "abstract" },
      { id: "surrealism", name: "Surrealism", value: "surrealism" },
      { id: "pop-art", name: "Pop Art", value: "pop art" },
      { id: "minimalist", name: "Minimalist", value: "minimalist" },
      { id: "impressionism", name: "Impressionism", value: "impressionism" },
      { id: "expressionism", name: "Expressionism", value: "expressionism" },
      { id: "comic", name: "Comic", value: "comic" },
      { id: "isometric", name: "Isometric", value: "isometric" },
      { id: "bauhaus", name: "Bauhaus", value: "bauhaus" },
      { id: "art-nouveau", name: "Art Nouveau", value: "art nouveau" },
      { id: "retro", name: "Retro", value: "retro" },
      { id: "vaporwave", name: "Vaporwave", value: "vaporwave" },
      { id: "cyberpunk", name: "Cyberpunk", value: "cyberpunk style" },
      { id: "steampunk", name: "Steampunk", value: "steampunk style" },
      { id: "ukiyo-e", name: "Ukiyo-e", value: "ukiyo-e" },
      { id: "low-poly", name: "Low Poly", value: "low poly" },
    ]
  },
  {
    id: "medium",
    name: "Medium",
    description: "The medium or technique used",
    options: [
      { id: "oil-painting", name: "Oil Painting", value: "oil painting" },
      { id: "watercolor", name: "Watercolor", value: "watercolor" },
      { id: "acrylic", name: "Acrylic", value: "acrylic" },
      { id: "pencil", name: "Pencil Drawing", value: "pencil drawing" },
      { id: "charcoal", name: "Charcoal", value: "charcoal" },
      { id: "ink", name: "Ink", value: "ink" },
      { id: "digital", name: "Digital", value: "digital" },
      { id: "photography", name: "Photography", value: "photography" },
      { id: "sculpture", name: "Sculpture", value: "sculpture" },
      { id: "3d-model", name: "3D Model", value: "3D model" },
      { id: "pastel", name: "Pastel", value: "pastel" },
      { id: "chalk", name: "Chalk", value: "chalk" },
      { id: "crayon", name: "Crayon", value: "crayon" },
      { id: "collage", name: "Collage", value: "collage" },
      { id: "gouache", name: "Gouache", value: "gouache" },
      { id: "vector", name: "Vector Art", value: "vector art" },
      { id: "linocut", name: "Linocut", value: "linocut" },
      { id: "lithograph", name: "Lithograph", value: "lithograph" },
      { id: "screen-print", name: "Screen Print", value: "screen print" },
      { id: "etching", name: "Etching", value: "etching" },
      { id: "airbrush", name: "Airbrush", value: "airbrush" },
      { id: "cgi", name: "CGI", value: "cgi" },
      { id: "embroidery", name: "Embroidery", value: "embroidery" },
      { id: "graffiti", name: "Graffiti", value: "graffiti" },
    ]
  },
  {
    id: "artists",
    name: "Artist Style",
    description: "Artists whose style influences the image (select multiple)",
    options: [
      { id: "van-gogh", name: "Vincent van Gogh", value: "Vincent van Gogh" },
      { id: "picasso", name: "Pablo Picasso", value: "Pablo Picasso" },
      { id: "monet", name: "Claude Monet", value: "Claude Monet" },
      { id: "dali", name: "Salvador Dalí", value: "Salvador Dalí" },
      { id: "warhol", name: "Andy Warhol", value: "Andy Warhol" },
      { id: "rembrandt", name: "Rembrandt", value: "Rembrandt" },
      { id: "da-vinci", name: "Leonardo da Vinci", value: "Leonardo da Vinci" },
      { id: "klimt", name: "Gustav Klimt", value: "Gustav Klimt" },
      { id: "mucha", name: "Alphonse Mucha", value: "Alphonse Mucha" },
      { id: "ross", name: "Bob Ross", value: "Bob Ross" },
      { id: "miyazaki", name: "Hayao Miyazaki", value: "Hayao Miyazaki" },
      { id: "greg-rutkowski", name: "Greg Rutkowski", value: "Greg Rutkowski" },
      { id: "artgerm", name: "Artgerm", value: "Artgerm" },
      { id: "james-gurney", name: "James Gurney", value: "James Gurney" },
      { id: "banksy", name: "Banksy", value: "Banksy" },
      { id: "moebius", name: "Moebius", value: "Moebius" },
      { id: "hockney", name: "David Hockney", value: "David Hockney" },
      { id: "kinkade", name: "Thomas Kinkade", value: "Thomas Kinkade" },
      { id: "frida", name: "Frida Kahlo", value: "Frida Kahlo" },
      { id: "hopper", name: "Edward Hopper", value: "Edward Hopper" },
      { id: "vermeer", name: "Johannes Vermeer", value: "Johannes Vermeer" },
      { id: "kandinsky", name: "Wassily Kandinsky", value: "Wassily Kandinsky" },
      { id: "matisse", name: "Henri Matisse", value: "Henri Matisse" },
      { id: "cezanne", name: "Paul Cézanne", value: "Paul Cézanne" },
      { id: "turner", name: "J.M.W. Turner", value: "J.M.W. Turner" },
      { id: "michelangelo", name: "Michelangelo", value: "Michelangelo" },
      { id: "caravaggio", name: "Caravaggio", value: "Caravaggio" },
      { id: "giger", name: "H.R. Giger", value: "H.R. Giger" },
    ]
  },
  {
    id: "photographers",
    name: "Photographer Style",
    description: "Photographers whose style influences the image (select multiple)",
    options: [
      { id: "annie-leibovitz", name: "Annie Leibovitz", value: "Annie Leibovitz" },
      { id: "ansel-adams", name: "Ansel Adams", value: "Ansel Adams" },
      { id: "steve-mccurry", name: "Steve McCurry", value: "Steve McCurry" },
      { id: "richard-avedon", name: "Richard Avedon", value: "Richard Avedon" },
      { id: "dorothea-lange", name: "Dorothea Lange", value: "Dorothea Lange" },
      { id: "henri-cartier-bresson", name: "Henri Cartier-Bresson", value: "Henri Cartier-Bresson" },
      { id: "cindy-sherman", name: "Cindy Sherman", value: "Cindy Sherman" },
      { id: "sally-mann", name: "Sally Mann", value: "Sally Mann" },
      { id: "sebastiao-salgado", name: "Sebastião Salgado", value: "Sebastião Salgado" },
      { id: "robert-capa", name: "Robert Capa", value: "Robert Capa" },
      { id: "diane-arbus", name: "Diane Arbus", value: "Diane Arbus" },
      { id: "helmut-newton", name: "Helmut Newton", value: "Helmut Newton" },
      { id: "irving-penn", name: "Irving Penn", value: "Irving Penn" },
      { id: "robert-frank", name: "Robert Frank", value: "Robert Frank" },
      { id: "william-eggleston", name: "William Eggleston", value: "William Eggleston" },
      { id: "peter-lindbergh", name: "Peter Lindbergh", value: "Peter Lindbergh" },
      { id: "platon", name: "Platon", value: "Platon" },
      { id: "steven-klein", name: "Steven Klein", value: "Steven Klein" },
      { id: "mario-testino", name: "Mario Testino", value: "Mario Testino" },
      { id: "tim-walker", name: "Tim Walker", value: "Tim Walker" },
      { id: "david-lachapelle", name: "David LaChapelle", value: "David LaChapelle" },
      { id: "terry-richardson", name: "Terry Richardson", value: "Terry Richardson" },
      { id: "juergen-teller", name: "Juergen Teller", value: "Juergen Teller" },
      { id: "ryan-mcginley", name: "Ryan McGinley", value: "Ryan McGinley" },
      { id: "nan-goldin", name: "Nan Goldin", value: "Nan Goldin" },
      { id: "tyler-mitchell", name: "Tyler Mitchell", value: "Tyler Mitchell" },
      { id: "petra-collins", name: "Petra Collins", value: "Petra Collins" },
      { id: "harley-weir", name: "Harley Weir", value: "Harley Weir" },
      { id: "dana-scruggs", name: "Dana Scruggs", value: "Dana Scruggs" },
      { id: "ellen-von-unwerth", name: "Ellen von Unwerth", value: "Ellen von Unwerth" },
      { id: "collier-schorr", name: "Collier Schorr", value: "Collier Schorr" },
      { id: "marilyn-minter", name: "Marilyn Minter", value: "Marilyn Minter" },
      { id: "campbell-addy", name: "Campbell Addy", value: "Campbell Addy" },
      { id: "bastiaan-woudt", name: "Bastiaan Woudt", value: "Bastiaan Woudt" },
      { id: "viviane-sassen", name: "Viviane Sassen", value: "Viviane Sassen" },
      { id: "nadine-ijewere", name: "Nadine Ijewere", value: "Nadine Ijewere" },
      { id: "mert-and-marcus", name: "Mert & Marcus", value: "Mert & Marcus" },
      { id: "inez-and-vinoodh", name: "Inez & Vinoodh", value: "Inez & Vinoodh" },
      { id: "rankin", name: "Rankin", value: "Rankin" },
      { id: "greg-williams", name: "Greg Williams", value: "Greg Williams" }
    ]
  },
  {
    id: "lighting",
    name: "Lighting",
    description: "Lighting conditions and effects",
    options: [
      { id: "natural", name: "Natural Lighting", value: "natural lighting" },
      { id: "studio", name: "Studio Lighting", value: "studio lighting" },
      { id: "dramatic", name: "Dramatic", value: "dramatic lighting" },
      { id: "soft", name: "Soft", value: "soft lighting" },
      { id: "harsh", name: "Harsh", value: "harsh lighting" },
      { id: "backlit", name: "Backlit", value: "backlit" },
      { id: "neon", name: "Neon", value: "neon lighting" },
      { id: "cinematic", name: "Cinematic", value: "cinematic lighting" },
      { id: "golden-hour", name: "Golden Hour", value: "golden hour lighting" },
      { id: "blue-hour", name: "Blue Hour", value: "blue hour lighting" },
      { id: "candlelight", name: "Candlelight", value: "candlelight" },
      { id: "moonlight", name: "Moonlight", value: "moonlight" },
      { id: "spotlight", name: "Spotlight", value: "spotlight" },
      { id: "ambient", name: "Ambient", value: "ambient lighting" },
      { id: "volumetric", name: "Volumetric", value: "volumetric lighting" },
      { id: "rim-light", name: "Rim Light", value: "rim light" },
      { id: "silhouette", name: "Silhouette", value: "silhouette lighting" },
      { id: "low-key", name: "Low Key", value: "low key lighting" },
      { id: "high-key", name: "High Key", value: "high key lighting" },
      { id: "chiaroscuro", name: "Chiaroscuro", value: "chiaroscuro lighting" },
      { id: "split", name: "Split Lighting", value: "split lighting" },
      { id: "loop", name: "Loop Lighting", value: "loop lighting" },
      { id: "butterfly", name: "Butterfly Lighting", value: "butterfly lighting" },
      { id: "rembrandt", name: "Rembrandt Lighting", value: "rembrandt lighting" },
    ]
  },
  {
    id: "mood",
    name: "Mood/Atmosphere",
    description: "The emotional tone or atmosphere",
    options: [
      { id: "peaceful", name: "Peaceful", value: "peaceful" },
      { id: "dramatic", name: "Dramatic", value: "dramatic" },
      { id: "mysterious", name: "Mysterious", value: "mysterious" },
      { id: "romantic", name: "Romantic", value: "romantic" },
      { id: "scary", name: "Scary", value: "scary" },
      { id: "melancholic", name: "Melancholic", value: "melancholic" },
      { id: "joyful", name: "Joyful", value: "joyful" },
      { id: "energetic", name: "Energetic", value: "energetic" },
      { id: "dreamy", name: "Dreamy", value: "dreamy" },
      { id: "ethereal", name: "Ethereal", value: "ethereal" },
      { id: "nostalgic", name: "Nostalgic", value: "nostalgic" },
      { id: "tense", name: "Tense", value: "tense" },
      { id: "tranquil", name: "Tranquil", value: "tranquil" },
      { id: "whimsical", name: "Whimsical", value: "whimsical" },
      { id: "ominous", name: "Ominous", value: "ominous" },
      { id: "serene", name: "Serene", value: "serene" },
      { id: "chaotic", name: "Chaotic", value: "chaotic" },
      { id: "eerie", name: "Eerie", value: "eerie" },
      { id: "magical", name: "Magical", value: "magical" },
      { id: "dark", name: "Dark", value: "dark mood" },
      { id: "hopeful", name: "Hopeful", value: "hopeful" },
      { id: "epic", name: "Epic", value: "epic" },
      { id: "solemn", name: "Solemn", value: "solemn" },
      { id: "playful", name: "Playful", value: "playful" },
    ]
  },
  {
    id: "colors",
    name: "Color Palette",
    description: "Dominant colors or color scheme (select multiple)",
    options: [
      { id: "vibrant", name: "Vibrant", value: "vibrant colors" },
      { id: "pastel", name: "Pastel", value: "pastel colors" },
      { id: "monochromatic", name: "Monochromatic", value: "monochromatic" },
      { id: "black-white", name: "Black & White", value: "black and white" },
      { id: "sepia", name: "Sepia", value: "sepia tones" },
      { id: "neon", name: "Neon", value: "neon colors" },
      { id: "earthy", name: "Earthy", value: "earthy tones" },
      { id: "cool", name: "Cool Tones", value: "cool tones" },
      { id: "warm", name: "Warm Tones", value: "warm tones" },
      { id: "red", name: "Red", value: "red dominant" },
      { id: "blue", name: "Blue", value: "blue dominant" },
      { id: "green", name: "Green", value: "green dominant" },
      { id: "yellow", name: "Yellow", value: "yellow dominant" },
      { id: "purple", name: "Purple", value: "purple dominant" },
      { id: "orange", name: "Orange", value: "orange dominant" },
      { id: "pink", name: "Pink", value: "pink dominant" },
      { id: "teal", name: "Teal", value: "teal dominant" },
      { id: "gold", name: "Gold", value: "gold accent" },
      { id: "silver", name: "Silver", value: "silver accent" },
      { id: "copper", name: "Copper", value: "copper accent" },
      { id: "iridescent", name: "Iridescent", value: "iridescent" },
      { id: "metallic", name: "Metallic", value: "metallic" },
      { id: "gradient", name: "Gradient", value: "gradient colors" },
      { id: "duotone", name: "Duotone", value: "duotone" },
    ]
  },
];
